### ISSUE TITLE
Fails to run in Android emulator. 

### ISSUE THREAD

**Issue by MBedrymmHg** [Baseflow/flutter-video-bloc#1]
Does not run on Android Emulator using Flutter 2.5. It fails with Codec Error. Works fine in IOS and Web.

Playback error
E/ExoPlayerImplInternal( 4168):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1280, 720, 25.0], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal( 4168):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 4168):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 4168):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4168):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal( 4168):       ... 3 more
E/ExoPlayerImplInternal( 4168):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal( 4168):       at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 4168):       at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:53)
E/ExoPlayerImplInternal( 4168):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 4168):    .....

**Comment by edmagnini** [comment]
Same issue here. Anyone knows how to fix it?
